# Generated by Django 4.0.1 on 2022-01-11 10:06

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('url', models.SlugField(verbose_name='Личная ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shortinfo', models.CharField(blank=True, max_length=150, verbose_name='Слоган')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/%y.%m.%d', verbose_name='Постер')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('published', models.DateField(default=datetime.date.today, verbose_name='Опубликованно')),
                ('rating', models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг')),
                ('views', models.SmallIntegerField(default=0, null=True, verbose_name='Просмотры')),
                ('url', models.SlugField(unique=True, verbose_name='Личная ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рассказ',
                'verbose_name_plural': 'Рассказы',
                'ordering': ['-published', '-rating'],
            },
        ),
    ]
