# Generated by Django 4.0.1 on 2022-01-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='opinion',
            new_name='status',
        ),
    ]
