# Generated by Django 4.0.1 on 2022-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_opinion_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_url',
            field=models.SlugField(max_length=150, null=True, verbose_name='Личная ссылка'),
        ),
    ]
