# Generated by Django 4.0.1 on 2022-01-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_rating',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_url',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Личная ссылка'),
        ),
    ]
