# Generated by Django 4.0.1 on 2022-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_profile_rating_alter_profile_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('reviewer', 'Критик'), ('writer', 'Писатель'), ('on_right_way', 'На пусти истинном'), ('junior_poet', 'Юный поэт')], default='on_right_way', max_length=150, null=True, verbose_name='Статус'),
        ),
    ]
