# Generated by Django 4.0.1 on 2022-01-26 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('reviewer', 'Критик'), ('writer', 'Писатель'), ('on_right_way', 'На пусти истинном'), ('junior_poet', 'Юный поэт')], default='on_right_way', max_length=40, null=True, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ProfileStoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='Лайк')),
                ('in_bookmarks', models.BooleanField(default=False, verbose_name='В закладках')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.story', verbose_name='История')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайки и закладки',
                'verbose_name_plural': 'Лайки и закладки',
            },
        ),
    ]
