# Generated by Django 4.0.1 on 2022-02-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_story_readers_alter_story_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='readers',
        ),
    ]
