# Generated by Django 4.0.1 on 2022-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_story_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='users/default.png', upload_to='users/%y.%m.%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('reviewer', 'Критик'), ('writer', 'Писатель'), ('on_right_way', 'На пути истинном'), ('junior_poet', 'Юный поэт')], default='on_right_way', max_length=40, null=True, verbose_name='Статус'),
        ),
    ]
