# Generated by Django 4.0.1 on 2022-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_profile_profile_picture_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='users/%y.%m.%d', verbose_name='Фотография'),
        ),
    ]
