# Generated by Django 4.0.1 on 2022-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='users/default.png', null=True, upload_to='users/%y.%m.%d', verbose_name='Фотография'),
        ),
    ]
