# Generated by Django 4.0.1 on 2022-02-23 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='readers',
            field=models.ManyToManyField(related_name='readers_stories', through='blog.ProfileStoryRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
