# Generated by Django 4.0.1 on 2022-02-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_story_readers_alter_story_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.SlugField(blank=True, unique=True, verbose_name='Личная ссылка'),
        ),
    ]
